version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: fitByte-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fitByte
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - forum_mysql_data:/var/lib/mysql

volumes:
  forum_mysql_data: